# This file is autogenerated, do not edit by hand!
{fetchgit}: {
  registryUrl = "https://github.com/JuliaRegistries/General.git";
  registryRev = "67bc6b19be176f29bbaa8df6e4d0044fcc5ba6ec";
  registrySha256 = "17xnq4lbmafbxkpxal9a0hz3rfcgf0hl7507yr9dv9562djxwklg";
  rootPackages = ["Distributions" "Gadfly" "LinearAlgebra"];
  closure = [{
  name = "AbstractFFTs";
  uuid = "621f4979-c628-5d54-868e-fcf4e3e8185c";
  path = "A/AbstractFFTs";
  replaceUrlInManifest = null;
  treehash = "485ee0867925449198280d4af84bdb46a2a404d0";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaMath/AbstractFFTs.jl.git"; rev = "485ee0867925449198280d4af84bdb46a2a404d0"; sha256 = "0083pwdyxjb04i330ir9pc8kmp4bwk59lx1jgc9qi05y8j7xzbp0"; };
} {
  name = "Adapt";
  uuid = "79e6a3ab-5dfb-504d-930d-738a2a938a0e";
  path = "A/Adapt";
  replaceUrlInManifest = null;
  treehash = "ffcfa2d345aaee0ef3d8346a073d5dd03c983ebe";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaGPU/Adapt.jl.git"; rev = "ffcfa2d345aaee0ef3d8346a073d5dd03c983ebe"; sha256 = "1z245s3z35ks9wblfzlnkck912a6pv3rc9n05zxba3sngwd7fa1s"; };
} {
  name = "Artifacts";
  uuid = "56f22d72-fd6d-98f1-02f0-08ddc0907c33";
  path = "A/Artifacts";
  replaceUrlInManifest = null;
  treehash = "c30985d8821e0cd73870b17b0ed0ce6dc44cb744";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaPackaging/Artifacts.jl.git"; rev = "c30985d8821e0cd73870b17b0ed0ce6dc44cb744"; sha256 = "0i0s26ypiwg6zyb3aqn9kiyiblkkab1mfac9plmq2jv4hggm4jfc"; };
} {
  name = "AxisAlgorithms";
  uuid = "13072b0f-2c55-5437-9ae7-d433b7a33950";
  path = "A/AxisAlgorithms";
  replaceUrlInManifest = null;
  treehash = "a4d07a1c313392a77042855df46c5f534076fab9";
  artifacts = {};
  src = fetchgit { url = "https://github.com/timholy/AxisAlgorithms.jl.git"; rev = "a4d07a1c313392a77042855df46c5f534076fab9"; sha256 = "00x85lnfln7xkfnirpplzyi8r6q92nfqwya8il156bf7b1pa20gk"; };
} {
  name = "Base64";
  uuid = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "CategoricalArrays";
  uuid = "324d7699-5711-5eae-9e2f-1d82baa6b597";
  path = "C/CategoricalArrays";
  replaceUrlInManifest = null;
  treehash = "2ac27f59196a68070e132b25713f9a5bbc5fa0d2";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaData/CategoricalArrays.jl.git"; rev = "2ac27f59196a68070e132b25713f9a5bbc5fa0d2"; sha256 = "0vh18x9h71gi5basg1n4kmfrkwwiqcaikbq30w9d3gmc77xqcjs8"; };
} {
  name = "ColorTypes";
  uuid = "3da002f7-5984-5a60-b8a6-cbb66c0b333f";
  path = "C/ColorTypes";
  replaceUrlInManifest = null;
  treehash = "5e9769a17f17b587c951d57ba4319782b40c3513";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaGraphics/ColorTypes.jl.git"; rev = "5e9769a17f17b587c951d57ba4319782b40c3513"; sha256 = "0d91pfwzmv9sjqh94xsvrvpl23y8nps57fl42v10xhkqwl26d58r"; };
} {
  name = "Colors";
  uuid = "5ae59095-9a9b-59fe-a467-6f913c188581";
  path = "C/Colors";
  replaceUrlInManifest = null;
  treehash = "ac5f2213e56ed8a34a3dd2f681f4df1166b34929";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaGraphics/Colors.jl.git"; rev = "ac5f2213e56ed8a34a3dd2f681f4df1166b34929"; sha256 = "156zsszgwh6bmznsan0zyha6yvcxw3c5mvc5vr2qfsgxbyh36ln6"; };
} {
  name = "Compat";
  uuid = "34da2185-b29b-5c13-b0c7-acf172513d20";
  path = "C/Compat";
  replaceUrlInManifest = null;
  treehash = "919c7f3151e79ff196add81d7f4e45d91bbf420b";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaLang/Compat.jl.git"; rev = "919c7f3151e79ff196add81d7f4e45d91bbf420b"; sha256 = "1m4r5i8mq29xjp3mllh6047n5a78sdyld57m15anrnsjgaapcgby"; };
} {
  name = "CompilerSupportLibraries_jll";
  uuid = "e66e0078-7015-5450-92f7-15fbd957f2ae";
  path = "C/CompilerSupportLibraries_jll";
  replaceUrlInManifest = null;
  treehash = "8e695f735fca77e9708e795eda62afdb869cbb70";
  artifacts = {
    "7c9ef733699a1d86b8a6073ed08a4457e3e790f7" = [{
      name = "CompilerSupportLibraries";
      url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.3+0/CompilerSupportLibraries.v0.3.3.x86_64-apple-darwin14-libgfortran5.tar.gz";
      sha256 = "e308cbb8e0b2b50635f98cf700b24743a2eb9d5c7726a99375ef31e096371642";
    }];
  };
  src = fetchgit { url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl.git"; rev = "8e695f735fca77e9708e795eda62afdb869cbb70"; sha256 = "0iqm61cjxilqcapz9z9w42qq799dmzfd92px2gysjdmny3v0qf4r"; };
} {
  name = "Compose";
  uuid = "a81c6b42-2e10-5240-aca2-a61377ecd94b";
  path = "C/Compose";
  replaceUrlInManifest = null;
  treehash = "c6461fc7c35a4bb8d00905df7adafcff1fe3a6bc";
  artifacts = {};
  src = fetchgit { url = "https://github.com/GiovineItalia/Compose.jl.git"; rev = "c6461fc7c35a4bb8d00905df7adafcff1fe3a6bc"; sha256 = "03xnff36fipj4fm3cc8j9sigjmkrcafnmwg0a67wayk4jppfrrvr"; };
} {
  name = "Contour";
  uuid = "d38c429a-6771-53c6-b99e-75d170b6e991";
  path = "C/Contour";
  replaceUrlInManifest = null;
  treehash = "9f02045d934dc030edad45944ea80dbd1f0ebea7";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaGeometry/Contour.jl.git"; rev = "9f02045d934dc030edad45944ea80dbd1f0ebea7"; sha256 = "0ai6lh5ap9qxhqm2k1pnkfbpm4b95d3v7izhyvrr9cxwbxfjv3vn"; };
} {
  name = "CoupledFields";
  uuid = "7ad07ef1-bdf2-5661-9d2b-286fd4296dac";
  path = "C/CoupledFields";
  replaceUrlInManifest = null;
  treehash = "6c9671364c68c1158ac2524ac881536195b7e7bc";
  artifacts = {};
  src = fetchgit { url = "https://github.com/Mattriks/CoupledFields.jl.git"; rev = "6c9671364c68c1158ac2524ac881536195b7e7bc"; sha256 = "0xrcp18z6ia7k3kjjzqksaw85fv5j58xy8nvlfxn7xlxr8y9f5jz"; };
} {
  name = "DataAPI";
  uuid = "9a962f9c-6df0-11e9-0e5d-c546b8b5ee8a";
  path = "D/DataAPI";
  replaceUrlInManifest = null;
  treehash = "dfb3b7e89e395be1e25c2ad6d7690dc29cc53b1d";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaData/DataAPI.jl.git"; rev = "dfb3b7e89e395be1e25c2ad6d7690dc29cc53b1d"; sha256 = "14sfvkz169zcbap3gdwpj16qsap783h86fd07flfxk822abam11w"; };
} {
  name = "DataStructures";
  uuid = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8";
  path = "D/DataStructures";
  replaceUrlInManifest = null;
  treehash = "4437b64df1e0adccc3e5d1adbc3ac741095e4677";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaCollections/DataStructures.jl.git"; rev = "4437b64df1e0adccc3e5d1adbc3ac741095e4677"; sha256 = "0hdqp8ipsqdw5bqqkdvz4j6n67x80sj5azr9vzyxwjfsgkfbnk2l"; };
} {
  name = "Dates";
  uuid = "ade2ca70-3891-5945-98fb-dc099432e06a";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "DelimitedFiles";
  uuid = "8bb1440f-4735-579b-a4ab-409b98df4dab";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "Distances";
  uuid = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7";
  path = "D/Distances";
  replaceUrlInManifest = null;
  treehash = "366715149014943abd71aa647a07a43314158b2d";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaStats/Distances.jl.git"; rev = "366715149014943abd71aa647a07a43314158b2d"; sha256 = "0sb73njqrq6700sq856sb2zfsmk4916b1dww32m5wsqk29cf53i4"; };
} {
  name = "Distributed";
  uuid = "8ba89e20-285c-5b6f-9357-94700520ee1b";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "Distributions";
  uuid = "31c24e10-a181-5473-b8eb-7969acd0382f";
  path = "D/Distributions";
  replaceUrlInManifest = null;
  treehash = "501c11d708917ca09ce357bed163dbaf0f30229f";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaStats/Distributions.jl.git"; rev = "501c11d708917ca09ce357bed163dbaf0f30229f"; sha256 = "19ahpqx43dr28fa5hr1dp5yvhq3122rps4clhslhgq9g3im9j4hq"; };
} {
  name = "DocStringExtensions";
  uuid = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae";
  path = "D/DocStringExtensions";
  replaceUrlInManifest = null;
  treehash = "50ddf44c53698f5e784bbebb3f4b21c5807401b1";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaDocs/DocStringExtensions.jl.git"; rev = "50ddf44c53698f5e784bbebb3f4b21c5807401b1"; sha256 = "16zlz0asj57l7mncl0chq9i0p7hibxh3f9xxk31q8ncxyzki5mk0"; };
} {
  name = "FFTW";
  uuid = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341";
  path = "F/FFTW";
  replaceUrlInManifest = null;
  treehash = "1b48dbde42f307e48685fa9213d8b9f8c0d87594";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaMath/FFTW.jl.git"; rev = "1b48dbde42f307e48685fa9213d8b9f8c0d87594"; sha256 = "1xgqy9zl9sw1bh5fgsh59dc9aafpp76zjlj99hjzq025n02z5nly"; };
} {
  name = "FFTW_jll";
  uuid = "f5851436-0d7a-5f13-b9de-f02708fd171a";
  path = "F/FFTW_jll";
  replaceUrlInManifest = null;
  treehash = "5a0d4b6a22a34d17d53543bd124f4b08ed78e8b0";
  artifacts = {
    "56539f59fc448ad7324cfcb69239ec6e010e340e" = [{
      name = "FFTW";
      url = "https://github.com/JuliaBinaryWrappers/FFTW_jll.jl/releases/download/FFTW-v3.3.9+7/FFTW.v3.3.9.x86_64-apple-darwin.tar.gz";
      sha256 = "70ecc4d8b0f99dcccf53719f8ca3576177936c11d0f79cb0881f2aa29d8e8d9d";
    }];
  };
  src = fetchgit { url = "https://github.com/JuliaBinaryWrappers/FFTW_jll.jl.git"; rev = "5a0d4b6a22a34d17d53543bd124f4b08ed78e8b0"; sha256 = "07qzcvhandsxl5hn0bxy1jv1ji2m70kxw3683vd8r3zdqq6swdf6"; };
} {
  name = "FillArrays";
  uuid = "1a297f60-69ca-5386-bcde-b61e274b549b";
  path = "F/FillArrays";
  replaceUrlInManifest = null;
  treehash = "502b3de6039d5b78c76118423858d981349f3823";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaArrays/FillArrays.jl.git"; rev = "502b3de6039d5b78c76118423858d981349f3823"; sha256 = "17vrycfmhzrrpdhm5qyi2hgw7s472nvd6j723l3arr8gwsh8havr"; };
} {
  name = "FixedPointNumbers";
  uuid = "53c48c17-4a7d-5ca2-90c5-79b7896eea93";
  path = "F/FixedPointNumbers";
  replaceUrlInManifest = null;
  treehash = "335bfdceacc84c5cdf16aadc768aa5ddfc5383cc";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaMath/FixedPointNumbers.jl.git"; rev = "335bfdceacc84c5cdf16aadc768aa5ddfc5383cc"; sha256 = "0j0n40n04q9sk68wh9jq90m6c67k4ws02k41djjzkrqmpzv4rcdi"; };
} {
  name = "Future";
  uuid = "9fa8497b-333b-5362-9e8d-4d0656e87820";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "Gadfly";
  uuid = "c91e804a-d5a3-530f-b6f0-dfbca275c004";
  path = "G/Gadfly";
  replaceUrlInManifest = null;
  treehash = "fce23cb26b95dd5b3b0fbc0d3e721a9a14620e5e";
  artifacts = {};
  src = fetchgit { url = "https://github.com/GiovineItalia/Gadfly.jl.git"; rev = "fce23cb26b95dd5b3b0fbc0d3e721a9a14620e5e"; sha256 = "0ya1lqji63mxgqfwzzwc7lwirb270v8yzh6cylqyyzwff4b9npxx"; };
} {
  name = "Grisu";
  uuid = "42e2da0e-8278-4e71-bc24-59509adca0fe";
  path = "G/Grisu";
  replaceUrlInManifest = null;
  treehash = "03d381f65183cb2d0af8b3425fde97263ce9a995";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaAttic/Grisu.jl.git"; rev = "03d381f65183cb2d0af8b3425fde97263ce9a995"; sha256 = "123z5wy4yzlqa2lbdrs15sj02hjdnckb1lyjcvaxjs4iz63lnpyv"; };
} {
  name = "Hexagons";
  uuid = "a1b4810d-1bce-5fbd-ac56-80944d57a21f";
  path = "H/Hexagons";
  replaceUrlInManifest = null;
  treehash = "de4a6f9e7c4710ced6838ca906f81905f7385fd6";
  artifacts = {};
  src = fetchgit { url = "https://github.com/GiovineItalia/Hexagons.jl.git"; rev = "de4a6f9e7c4710ced6838ca906f81905f7385fd6"; sha256 = "0470ras38wflg5vwhc2qnwwbkan4ill5w9dy2724rgigm6sfidyd"; };
} {
  name = "IndirectArrays";
  uuid = "9b13fd28-a010-5f03-acff-a1bbcff69959";
  path = "I/IndirectArrays";
  replaceUrlInManifest = null;
  treehash = "c2a145a145dc03a7620af1444e0264ef907bd44f";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaArrays/IndirectArrays.jl.git"; rev = "c2a145a145dc03a7620af1444e0264ef907bd44f"; sha256 = "0l0jq0jnr9z3k431ni82xycq7mqapgxrbrx4yyk6lycvi41ipm4s"; };
} {
  name = "IntelOpenMP_jll";
  uuid = "1d5cc7b8-4909-519e-a0f8-d0f5ad9712d0";
  path = "I/IntelOpenMP_jll";
  replaceUrlInManifest = null;
  treehash = "d979e54b71da82f3a65b62553da4fc3d18c9004c";
  artifacts = {
    "e76af028a823f7e7c18226c8079d03035c2e4c46" = [{
      name = "IntelOpenMP";
      url = "https://github.com/JuliaBinaryWrappers/IntelOpenMP_jll.jl/releases/download/IntelOpenMP-v2018.0.3+2/IntelOpenMP.v2018.0.3.x86_64-apple-darwin.tar.gz";
      sha256 = "a6b58de42a450fa0253bbd417572e8f1549ebe5aaddae3bf088b2e29007de1bd";
    }];
  };
  src = fetchgit { url = "https://github.com/JuliaBinaryWrappers/IntelOpenMP_jll.jl.git"; rev = "d979e54b71da82f3a65b62553da4fc3d18c9004c"; sha256 = "0gwxfmd1vrn1bjdivm7yjpwsjmw79cp7mirjiv8pr6xva1h3l3g7"; };
} {
  name = "InteractiveUtils";
  uuid = "b77e0a4c-d291-57a0-90e8-8db25a27a240";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "Interpolations";
  uuid = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59";
  path = "I/Interpolations";
  replaceUrlInManifest = null;
  treehash = "eb1dd6d5b2275faaaa18533e0fc5f9171cec25fa";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaMath/Interpolations.jl.git"; rev = "eb1dd6d5b2275faaaa18533e0fc5f9171cec25fa"; sha256 = "04zpqhpmahb4f38iy5h0ahaakzpnnbs8kh100m4zpc1wqsp2d4nn"; };
} {
  name = "IterTools";
  uuid = "c8e1da08-722c-5040-9ed9-7db0dc04731e";
  path = "I/IterTools";
  replaceUrlInManifest = null;
  treehash = "05110a2ab1fc5f932622ffea2a003221f4782c18";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaCollections/IterTools.jl.git"; rev = "05110a2ab1fc5f932622ffea2a003221f4782c18"; sha256 = "0haf974kcqj6arv4if97ahs4w3dmvslh6ab3hl57r9s41ic36xdq"; };
} {
  name = "JLLWrappers";
  uuid = "692b3bcd-3c85-4b1f-b108-f13ce0eb3210";
  path = "J/JLLWrappers";
  replaceUrlInManifest = null;
  treehash = "a431f5f2ca3f4feef3bd7a5e94b8b8d4f2f647a0";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaPackaging/JLLWrappers.jl.git"; rev = "a431f5f2ca3f4feef3bd7a5e94b8b8d4f2f647a0"; sha256 = "1sj3mi2dcc13apqfpy401wic5n0pgbck1p98b2g3zw0mln9s83m4"; };
} {
  name = "JSON";
  uuid = "682c06a0-de6a-54ab-a142-c8b1cf79cde6";
  path = "J/JSON";
  replaceUrlInManifest = null;
  treehash = "81690084b6198a2e1da36fcfda16eeca9f9f24e4";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaIO/JSON.jl.git"; rev = "81690084b6198a2e1da36fcfda16eeca9f9f24e4"; sha256 = "1f9k613kbknmp4fgjxvjaw4d5sfbx8a5hmcszmp1w9rqfqngjx9m"; };
} {
  name = "Juno";
  uuid = "e5e0dc1b-0480-54bc-9374-aad01c23163d";
  path = "J/Juno";
  replaceUrlInManifest = null;
  treehash = "07cb43290a840908a771552911a6274bc6c072c7";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JunoLab/Juno.jl.git"; rev = "07cb43290a840908a771552911a6274bc6c072c7"; sha256 = "02ryj5blnrmck3jisrpwn1x563i7rsg65d7zms52njsvv499gygk"; };
} {
  name = "KernelDensity";
  uuid = "5ab0869b-81aa-558d-bb23-cbf5423bbe9b";
  path = "K/KernelDensity";
  replaceUrlInManifest = null;
  treehash = "09aeec87bdc9c1fa70d0b508dfa94a21acd280d9";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaStats/KernelDensity.jl.git"; rev = "09aeec87bdc9c1fa70d0b508dfa94a21acd280d9"; sha256 = "00w02xkkj2cj173zyps26iz1a7qa2db16dzhidbm3ixhkis8ys70"; };
} {
  name = "LazyArtifacts";
  uuid = "4af54fe1-eca0-43a8-85a7-787d91b784e3";
  path = "L/LazyArtifacts";
  replaceUrlInManifest = null;
  treehash = "4bb5499a1fc437342ea9ab7e319ede5a457c0968";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaPackaging/LazyArtifacts.jl.git"; rev = "4bb5499a1fc437342ea9ab7e319ede5a457c0968"; sha256 = "0qln5pq2zm68wgm104cxyviiql8xkv7rf68hivar2b7x2a8vwnk0"; };
} {
  name = "LibGit2";
  uuid = "76f85450-5226-5b5a-8eaa-529ad045b433";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "Libdl";
  uuid = "8f399da3-3557-5675-b5ff-fb832c97cbdb";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "LinearAlgebra";
  uuid = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "Loess";
  uuid = "4345ca2d-374a-55d4-8d30-97f9976e7612";
  path = "L/Loess";
  replaceUrlInManifest = null;
  treehash = "b5254a86cf65944c68ed938e575f5c81d5dfe4cb";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaStats/Loess.jl.git"; rev = "b5254a86cf65944c68ed938e575f5c81d5dfe4cb"; sha256 = "0x31173frxj5bh9hy3w39s58rvcl3jblddp1xsgzspl9m82zbds9"; };
} {
  name = "Logging";
  uuid = "56ddb016-857b-54e1-b83d-db4d58db5568";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "MKL_jll";
  uuid = "856f044c-d86e-5d09-b602-aeab76dc8ba7";
  path = "M/MKL_jll";
  replaceUrlInManifest = null;
  treehash = "c253236b0ed414624b083e6b72bfe891fbd2c7af";
  artifacts = {
    "073ff95e2c63501547247d6e1321bf4ee2a78933" = [{
      name = "MKL";
      url = "https://github.com/JuliaBinaryWrappers/MKL_jll.jl/releases/download/MKL-v2021.1.1+1/MKL.v2021.1.1.x86_64-apple-darwin.tar.gz";
      sha256 = "b7a5dd32e4a005a752bc4c3e6d425bf3b5bb1861730bbc4214216aa2c520f42d";
    }];
  };
  src = fetchgit { url = "https://github.com/JuliaBinaryWrappers/MKL_jll.jl.git"; rev = "c253236b0ed414624b083e6b72bfe891fbd2c7af"; sha256 = "1h3z0jid9wjz7if0qh54f200nyb17gc6cw1l66dljr0b6zgxj3zy"; };
} {
  name = "MacroTools";
  uuid = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09";
  path = "M/MacroTools";
  replaceUrlInManifest = null;
  treehash = "6a8a2a625ab0dea913aba95c11370589e0239ff0";
  artifacts = {};
  src = fetchgit { url = "https://github.com/FluxML/MacroTools.jl.git"; rev = "6a8a2a625ab0dea913aba95c11370589e0239ff0"; sha256 = "0k4z2hyasd9cwxf4l61zk3w4ajs44k69wx6z1ghdn8f5p8xy217f"; };
} {
  name = "Markdown";
  uuid = "d6f4376e-aef5-505a-96c1-9c027394607a";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "Measures";
  uuid = "442fdcdd-2543-5da2-b0f3-8c86c306513e";
  path = "M/Measures";
  replaceUrlInManifest = null;
  treehash = "e498ddeee6f9fdb4551ce855a46f54dbd900245f";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaGraphics/Measures.jl.git"; rev = "e498ddeee6f9fdb4551ce855a46f54dbd900245f"; sha256 = "0j34psrdijnqqn9zv0r2sknr1p9q0mmbjvjhmjra37bb5fh2gk8l"; };
} {
  name = "Media";
  uuid = "e89f7d12-3494-54d1-8411-f7d8b9ae1f27";
  path = "M/Media";
  replaceUrlInManifest = null;
  treehash = "75a54abd10709c01f1b86b84ec225d26e840ed58";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JunoLab/Media.jl.git"; rev = "75a54abd10709c01f1b86b84ec225d26e840ed58"; sha256 = "05jq9j3vs8yfj2lwz3sh1vk5rha06xdcikp9s2q3dn316vryy6di"; };
} {
  name = "Missings";
  uuid = "e1d29d7a-bbdc-5cf2-9ac0-f12de2c33e28";
  path = "M/Missings";
  replaceUrlInManifest = null;
  treehash = "f8c673ccc215eb50fcadb285f522420e29e69e1c";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaData/Missings.jl.git"; rev = "f8c673ccc215eb50fcadb285f522420e29e69e1c"; sha256 = "1qsnvpmqrps631yvka11hb5jcsfskgpn29c99fvm73vd9xqp6cin"; };
} {
  name = "Mmap";
  uuid = "a63ad114-7e13-5084-954f-fe012c677804";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "OffsetArrays";
  uuid = "6fe1bfb0-de20-5000-8ca7-80f57d26f881";
  path = "O/OffsetArrays";
  replaceUrlInManifest = null;
  treehash = "b3dfef5f2be7d7eb0e782ba9146a5271ee426e90";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaArrays/OffsetArrays.jl.git"; rev = "b3dfef5f2be7d7eb0e782ba9146a5271ee426e90"; sha256 = "064vb0w6harkgqa5wx1794yxfpl8ks2yl0v2yqz1f0pc2hl64rxg"; };
} {
  name = "OpenSpecFun_jll";
  uuid = "efe28fd5-8261-553b-a9e1-b2916fc3738e";
  path = "O/OpenSpecFun_jll";
  replaceUrlInManifest = null;
  treehash = "9db77584158d0ab52307f8c04f8e7c08ca76b5b3";
  artifacts = {
    "fcacf68db172fe1722facf228d64ab091ee037e6" = [{
      name = "OpenSpecFun";
      url = "https://github.com/JuliaBinaryWrappers/OpenSpecFun_jll.jl/releases/download/OpenSpecFun-v0.5.3+3/OpenSpecFun.v0.5.3.x86_64-apple-darwin14-libgfortran5.tar.gz";
      sha256 = "e261491ce3e8f2ac1181db455a3d5e2c0208132636780d73b61947ee708682b6";
    }];
  };
  src = fetchgit { url = "https://github.com/JuliaBinaryWrappers/OpenSpecFun_jll.jl.git"; rev = "9db77584158d0ab52307f8c04f8e7c08ca76b5b3"; sha256 = "0bl2gcgndsbiwhwy8fl070cjm1fyf9kxj6gkikgirmzgjl29iakn"; };
} {
  name = "OrderedCollections";
  uuid = "bac558e1-5e72-5ebc-8fee-abe8a469f55d";
  path = "O/OrderedCollections";
  replaceUrlInManifest = null;
  treehash = "4fa2ba51070ec13fcc7517db714445b4ab986bdf";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaCollections/OrderedCollections.jl.git"; rev = "4fa2ba51070ec13fcc7517db714445b4ab986bdf"; sha256 = "1mc0q32mcgawc9161xrpnrsrrn6jli1rhfbslv4f4fii94q78wd4"; };
} {
  name = "PDMats";
  uuid = "90014a1f-27ba-587c-ab20-58faa44d9150";
  path = "P/PDMats";
  replaceUrlInManifest = null;
  treehash = "95a4038d1011dfdbde7cecd2ad0ac411e53ab1bc";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaStats/PDMats.jl.git"; rev = "95a4038d1011dfdbde7cecd2ad0ac411e53ab1bc"; sha256 = "0lkivy3lw62wlw04scl3hdfdmwjz2kfa29h73akc0d53qvq36ji7"; };
} {
  name = "Parsers";
  uuid = "69de0a69-1ddd-5017-9359-2bf0b02dc9f0";
  path = "P/Parsers";
  replaceUrlInManifest = null;
  treehash = "223a825cccef2228f3fdbf2ecc7ca93363059073";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaData/Parsers.jl.git"; rev = "223a825cccef2228f3fdbf2ecc7ca93363059073"; sha256 = "0kwa1i3cbqhm4xpx0dwxy2dqyn7n63v0xg398hbw6wzz8ijj3b43"; };
} {
  name = "Pkg";
  uuid = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "Printf";
  uuid = "de0858da-6303-5e67-8744-51eddeeeb8d7";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "Profile";
  uuid = "9abbd945-dff8-562f-b5e8-e1ebf5ef1b79";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "QuadGK";
  uuid = "1fd47b50-473d-5c70-9696-f719f8f3bcdc";
  path = "Q/QuadGK";
  replaceUrlInManifest = null;
  treehash = "12fbe86da16df6679be7521dfb39fbc861e1dc7b";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaMath/QuadGK.jl.git"; rev = "12fbe86da16df6679be7521dfb39fbc861e1dc7b"; sha256 = "1hy0629yai6xflgxaflk9764lzr1lzhlghimxk1aqi212q9c6n33"; };
} {
  name = "REPL";
  uuid = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "Random";
  uuid = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "Ratios";
  uuid = "c84ed2f1-dad5-54f0-aa8e-dbefe2724439";
  path = "R/Ratios";
  replaceUrlInManifest = null;
  treehash = "37d210f612d70f3f7d57d488cb3b6eff56ad4e41";
  artifacts = {};
  src = fetchgit { url = "https://github.com/timholy/Ratios.jl.git"; rev = "37d210f612d70f3f7d57d488cb3b6eff56ad4e41"; sha256 = "1a4fd4jq4qjply29rkwg3m1clfndjsbckj1b1dab1bc35h2c6yxh"; };
} {
  name = "Reexport";
  uuid = "189a3867-3050-52da-a836-e630ba90ab69";
  path = "R/Reexport";
  replaceUrlInManifest = null;
  treehash = "57d8440b0c7d98fc4f889e478e80f268d534c9d5";
  artifacts = {};
  src = fetchgit { url = "https://github.com/simonster/Reexport.jl.git"; rev = "57d8440b0c7d98fc4f889e478e80f268d534c9d5"; sha256 = "1yhhja1zz6dy5f4fd19bdwd6jwgj7q4w3avzgyg1hjhmdl8jrh0s"; };
} {
  name = "Requires";
  uuid = "ae029012-a4dd-5104-9daa-d747884805df";
  path = "R/Requires";
  replaceUrlInManifest = null;
  treehash = "4036a3bd08ac7e968e27c203d45f5fff15020621";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaPackaging/Requires.jl.git"; rev = "4036a3bd08ac7e968e27c203d45f5fff15020621"; sha256 = "03hyfy7c0ma45b0y756j76awi3az2ii4bz4s8cxm3xw9yy1z7b01"; };
} {
  name = "Rmath";
  uuid = "79098fc4-a85e-5d69-aa6a-4863f24498fa";
  path = "R/Rmath";
  replaceUrlInManifest = null;
  treehash = "86c5647b565873641538d8f812c04e4c9dbeb370";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaStats/Rmath.jl.git"; rev = "86c5647b565873641538d8f812c04e4c9dbeb370"; sha256 = "1745xajy5c8hdcy1hgi2rr9lrapr55hp0jm2dcb1ksyskvm5drsr"; };
} {
  name = "Rmath_jll";
  uuid = "f50d1b31-88e8-58de-be2c-1cc44531875f";
  path = "R/Rmath_jll";
  replaceUrlInManifest = null;
  treehash = "d76185aa1f421306dec73c057aa384bad74188f0";
  artifacts = {
    "477d5f3b600ea3228be99f17f05a0a04d7883e4f" = [{
      name = "Rmath";
      url = "https://github.com/JuliaBinaryWrappers/Rmath_jll.jl/releases/download/Rmath-v0.2.2+1/Rmath.v0.2.2.x86_64-apple-darwin14.tar.gz";
      sha256 = "11f2d106dbb0f07554cde70e421584a4a7b501842dd20bff79bbcbfbf400fe50";
    }];
  };
  src = fetchgit { url = "https://github.com/JuliaBinaryWrappers/Rmath_jll.jl.git"; rev = "d76185aa1f421306dec73c057aa384bad74188f0"; sha256 = "13wvx4n0ai7bsda3rvlw8xbqwdbdwhjijbgjgl0k2yzq5l8x5dmh"; };
} {
  name = "SHA";
  uuid = "ea8e919c-243c-51af-8825-aaa63cd721ce";
  path = "S/SHA";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "Serialization";
  uuid = "9e88b42a-f829-5b0c-bbe9-9e923198166b";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "SharedArrays";
  uuid = "1a1011a3-84de-559e-8e89-a11a2f7dc383";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "Showoff";
  uuid = "992d4aef-0814-514b-bc4d-f2e9a6c4116f";
  path = "S/Showoff";
  replaceUrlInManifest = null;
  treehash = "ee010d8f103468309b8afac4abb9be2e18ff1182";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaGraphics/Showoff.jl.git"; rev = "ee010d8f103468309b8afac4abb9be2e18ff1182"; sha256 = "0g9wqn9g3zravjc7bvdbf2cpmafy2gfw7s9bvrl7cdz3vpd4sy0x"; };
} {
  name = "Sockets";
  uuid = "6462fe0b-24de-5631-8697-dd941f90decc";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "SortingAlgorithms";
  uuid = "a2af1166-a08f-5f64-846c-94a0d3cef48c";
  path = "S/SortingAlgorithms";
  replaceUrlInManifest = null;
  treehash = "03f5898c9959f8115e30bc7226ada7d0df554ddd";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaCollections/SortingAlgorithms.jl.git"; rev = "03f5898c9959f8115e30bc7226ada7d0df554ddd"; sha256 = "1nz96sccgl6h6aknck59gmy1yrzx356kk9z68svj2g6yialprv1j"; };
} {
  name = "SparseArrays";
  uuid = "2f01184e-e22b-5df5-ae63-d93ebab69eaf";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "SpecialFunctions";
  uuid = "276daf66-3868-5448-9aa4-cd146d93841b";
  path = "S/SpecialFunctions";
  replaceUrlInManifest = null;
  treehash = "d8d8b8a9f4119829410ecd706da4cc8594a1e020";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaMath/SpecialFunctions.jl.git"; rev = "d8d8b8a9f4119829410ecd706da4cc8594a1e020"; sha256 = "1m0f3g6ikfrg85cbizq6xafg5r1r0db0x91y85i6czzmimk3156w"; };
} {
  name = "StaticArrays";
  uuid = "90137ffa-7385-5640-81b9-e52037218182";
  path = "S/StaticArrays";
  replaceUrlInManifest = null;
  treehash = "da4cf579416c81994afd6322365d00916c79b8ae";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaArrays/StaticArrays.jl.git"; rev = "da4cf579416c81994afd6322365d00916c79b8ae"; sha256 = "1h2biy5pjikg29rms0302gmds1q3i243yaaabmxddkyay67srms4"; };
} {
  name = "Statistics";
  uuid = "10745b16-79ce-11e8-11f9-7d13ad32a3b2";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "StatsBase";
  uuid = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91";
  path = "S/StatsBase";
  replaceUrlInManifest = null;
  treehash = "400aa43f7de43aeccc5b2e39a76a79d262202b76";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaStats/StatsBase.jl.git"; rev = "400aa43f7de43aeccc5b2e39a76a79d262202b76"; sha256 = "1vc1dqi3zbza7dj5znqqwkv0k1zdrkqikza6fvxh3rps20g7wfrp"; };
} {
  name = "StatsFuns";
  uuid = "4c63d2b9-4356-54db-8cca-17b64c39e42c";
  path = "S/StatsFuns";
  replaceUrlInManifest = null;
  treehash = "3b9f665c70712af3264b61c27a7e1d62055dafd1";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaStats/StatsFuns.jl.git"; rev = "3b9f665c70712af3264b61c27a7e1d62055dafd1"; sha256 = "0fhkx4clxlfixlb9hw7bsljfkv468k2y9s3f2cpaz7f5qbvgkmmq"; };
} {
  name = "StructTypes";
  uuid = "856f2bd8-1eba-4b0a-8007-ebc267875bd4";
  path = "S/StructTypes";
  replaceUrlInManifest = null;
  treehash = "d7f4287dbc1e590265f50ceda1b40ed2bb31bbbb";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaData/StructTypes.jl.git"; rev = "d7f4287dbc1e590265f50ceda1b40ed2bb31bbbb"; sha256 = "0mzmi8xx0rvwp7mw2d64j73vz06l9q5jyczw84c1xf63a5m1z3f6"; };
} {
  name = "SuiteSparse";
  uuid = "4607b0f0-06f3-5cda-b6b1-a6196a1729e9";
  path = "S/SuiteSparse";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "Test";
  uuid = "8dfed614-e22c-5e08-85e1-65c5234f0b40";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "UUIDs";
  uuid = "cf7118a7-6976-5b1a-9a39-7adc72f591a4";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "Unicode";
  uuid = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "WoodburyMatrices";
  uuid = "efce3f68-66dc-5838-9240-27a6d6f5f9b6";
  path = "W/WoodburyMatrices";
  replaceUrlInManifest = null;
  treehash = "59e2ad8fd1591ea019a5259bd012d7aee15f995c";
  artifacts = {};
  src = fetchgit { url = "https://github.com/timholy/WoodburyMatrices.jl.git"; rev = "59e2ad8fd1591ea019a5259bd012d7aee15f995c"; sha256 = "04yykivi8zrbryxlmb0p5xa6lma8iq22r5s863117dnnqj5gaffd"; };
}];
}
